[package]

name = "spin"
version = "0.3.5"
authors = [ "Mathijs van de Nes <git@mathijs.vd-nes.nl>",
            "John Ericson <John_Ericson@Yahoo.com>" ]
license = "MIT"
repository = "https://github.com/mvdnes/spinlock-rs.git"
documentation = "https://mvdnes.github.io/rust-docs/spinlock-rs/spin/index.html"
keywords = ["spinlock", "mutex", "rwlock"]
description = """
Synchronization primitives based on spinning.
They may contain data,
They are usable without `std`
and static initializers are available.
"""

[dependencies]
core = { path = "../../rust-libs/core" }
